services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py

  - type: worker
    name: monitor-termins
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor.py
